export default[
    {
        src:'',
        name:'apple',
        id:1,
        title:'',
        subtitle:'',
        price:4,
        quantity:3
    },
    {
        src:'',
        name:'orange',
        title:'',
        subtitle:'',
        id:2,
        price:14,
        quantity:4
    },
    {
        src:'',
        name:'banana',
        title:'',
        subtitle:'',
        id:3,
        price:8,
        quantity:3
    },
    {
        src:'',
        name:'pencil',
        title:'',
        subtitle:'',
        id:4,
        price:5,
        quantity:2
    },
    {
        src:'',
        name:'bag',
        id:5,
        title:'',
        subtitle:'',
        price:40,
        quantity:2
    },
    {
        src:'',
        name:'tablet',
        id:6,
        title:'',
        subtitle:'',
        price:34,
        quantity:1
    },
    {
        src:'',
        name:'ooops',
        id:7,
        title:'',
        subtitle:'',
        price:77,
        quantity:6
    },
    {
        src:'',
        name:'wallet',
        id:8,
        title:'',
        subtitle:'',
        price:41,
        quantity:1
    }
]